services:
  email-service:
    build:
      context: ..
      dockerfile: EmailService/Dockerfile
    container_name: email-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=intellilect-mq
      - EmailSettings__SenderName=IntelliLect
      - EmailSettings__SenderEmail=bolmangosy@gmail.com
      - EmailSettings__AppPassword=iqfjjwgmrqezbshi
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
    depends_on:
      intellilect-mq:
        condition: service_healthy
    networks:
      - intellilect-net
