name: intellilect-platform

include:
  - path: ./UserManagementService/docker-compose.unit.yml
  - path: ./EmailService/docker-compose.unit.yml
  - path: ./ClassroomService/docker-compose.unit.yml
  - path: ./StreamingService/docker-compose.unit.yml

services:
  intellilect-mq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=jafar.mahmood
      - RABBITMQ_DEFAULT_PASS=Jafar123!
    container_name: intellilect-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - intellilect-net

  intellilect-s3:
    image: minio/minio:latest
    container_name: intellilect-s3
    environment:
      - MINIO_ROOT_USER=testuser
      - MINIO_ROOT_PASSWORD=testpassword123!
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - intellilect-net
    volumes:
      - s3_data:/data

  gateway:
    image: nginx:latest
    container_name: intellilect-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - user-service
      - classroom-service
    networks:
      - intellilect-net

networks:
  intellilect-net:
    driver: bridge

volumes:
  user_db_data:
  classroom_db_data:
  s3_data:
