name: intellilect-platform

include:
  - path: ./UserManagementService/docker-compose.unit.yml
  - path: ./ClassroomService/docker-compose.unit.yml
  - path: ./StreamingService/docker-compose.unit.yml

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: intellilect-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - intellilect-net

  localstack:
    image: localstack/localstack:latest
    container_name: intellilect-s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    networks:
      - intellilect-net

  gateway:
    image: nginx:latest
    container_name: intellilect-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - user-service
      - classroom-service
    networks:
      - intellilect-net

networks:
  intellilect-net:
    driver: bridge

volumes:
  user_db_data:
  classroom_db_data:
