worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    sendfile on;

    upstream user_service {
        server user-management-service:8080;
    }

    server {
        listen 80;

        # Unified API Route
        location /api/ {
            proxy_pass         http://user_service/api/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # 2. Scalar UI
        location /scalar {
            proxy_pass         http://user_service;
            proxy_set_header   Host $host;
        }

        # 3. OpenAPI Docs
        location /openapi {
            proxy_pass         http://user_service;
            proxy_set_header   Host $host;
        }

        # 4. Gateway Health
        location /health {
            return 200 'Gateway is alive';
            add_header Content-Type text/plain;
        }
    }
}