worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    sendfile on;

    upstream user_service {
        server user-management-service:8080;
    }

    upstream classroom_service {
        server classroom-service:8080;
    }

    upstream streaming_service {
        server streaming-service:8080;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass         http://user_service/api/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /api/classrooms {
            proxy_pass http://classroom-service:8080;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }

        # Route for REST API calls (Join/Leave/History)
    location /api/streams {
        proxy_pass         http://streaming_service/api/streams; 
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Route for SignalR WebSockets (Chat/Reactions/Hand Raise)
    location /hubs/stream {
        proxy_pass         http://streaming_service/hubs/stream;
        
        # Mandatory WebSocket headers
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        
        # Standard headers
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
    }

        location /scalar {
            proxy_pass         http://user_service;
            proxy_set_header   Host $host;
        }

        location /openapi {
            proxy_pass         http://user_service;
            proxy_set_header   Host $host;
        }

        location /health {
            return 200 'Gateway is alive';
            add_header Content-Type text/plain;
        }
    }
}