<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../UserManagementService.Domain/UserManagementService.Domain.csproj" />
    <ProjectReference Include="../../../EmailService/src/EmailService.Contracts/EmailService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common/" />
    <Folder Include="Common/Mappings/" />
    <Folder Include="Common/Messages/" />
    <Folder Include="Manamgenet/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MassTransit.Abstractions" Version="8.1.3" />
  </ItemGroup>

</Project>
