services:
  streaming-db:
    image: postgres:17-alpine
    container_name: streaming-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Jafar123!
      - POSTGRES_DB=streaming_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d streaming_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    networks:
      - intellilect-net
    volumes:
      - streaming_db_data:/var/lib/postgresql/data

  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command:
      - --dev
      - --config
      - /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml
    environment:
      - LIVEKIT_NODE_IP=192.168.1.104
      - LiveKit__ApiKey=devkey
      - LiveKit__ApiSecret=super_secret_livekit_key_for_development
      - LiveKit__Host=ws://localhost:7880
    ports:
      - "7880:7880" # HTTP/Signal
      - "7881:7881" # WebRTC over TCP
      - "7882:7882/udp" # WebRTC over UDP (CRITICAL)
    networks:
      - intellilect-net

  streaming-service:
    build:
      context: ..
      dockerfile: StreamingService/Dockerfile
    container_name: streaming-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=streaming-db;Port=5432;Database=streaming_db;Username=postgres;Password=Jafar123!
      - RabbitMq__Host=intellilect-mq
      - RabbitMq__Username=jafar.mahmood
      - RabbitMq__Password=Jafar123!
      - Jwt__SecretKey=MY_SUPER_DUPER_STRONG_UNEXPECTED_SECRET_KEY
      - Jwt__Issuer=IntelliLect
      - Jwt__Audience=IntelliLect
      - LiveKit__ApiKey=devkey
      - LiveKit__ApiSecret=super_secret_livekit_key_for_development
      - LiveKit__Host=ws://localhost:7880
    depends_on:
      streaming-db:
        condition: service_healthy
      intellilect-mq:
        condition: service_healthy
      livekit-server:
        condition: service_started
    networks:
      - intellilect-net

volumes:
  streaming_db_data:
