services:
  classroom-db:
    image: postgres:latest
    container_name: classroom-db
    environment:
      POSTGRES_DB: classroomdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jafar123!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d classroomdb" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - intellilect-net

  classroom-service:
    build:
      context: ..
      dockerfile: ClassroomService/Dockerfile
    container_name: classroom-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=classroom-db;Port=5432;Database=classroomdb;Username=postgres;Password=Jafar123!
      - RabbitMq__Host=intellilect-mq
      - S3Settings__BucketName=intellilect-files
      - S3Settings__ServiceUrl=http://intellilect-s3:9000
      - Jwt__SecretKey=MY_SUPER_DUPER_STRONG_UNEXPECTED_SECRET_KEY
      - Jwt__Issuer=IntelliLect
      - Jwt__Audience=IntelliLect
    depends_on:
      classroom-db:
        condition: service_healthy
      intellilect-mq:
        condition: service_healthy
    networks:
      - intellilect-net

volumes:
  classroom_db_data:
